format:
  docx:
    csl: american-chemical-society.csl
    reference-doc: template.docx
  pdf:
    csl: american-chemical-society.csl
    cite-method: natbib
  html:
    csl: american-chemical-society.csl
